# Uncomment the next line to define a global platform for your project
workspace 'ChatUIKitTest'
platform :ios, '12.1'
use_frameworks!


target 'ChatUIKittest' do
  project 'ChatUIKittest/ChatUIKittest.xcodeproj'
  use_frameworks!
  inherit! :search_paths
    # Pods for testing
  pod 'ChatUIKit', :path => '../.'
end

target 'ChatUIKittestUITests' do
    project 'ChatUIKittest/ChatUIKittest.xcodeproj'
    use_frameworks!
    inherit! :search_paths
    # Pods for testing
    pod 'ChatUIKit', :path => '../.'
end

target 'ChatUIKittestTests' do
    project 'ChatUIKittest/ChatUIKittest.xcodeproj'
    use_frameworks!
    inherit! :search_paths
    # Pods for testing
    pod 'ChatUIKit', :path => '../.'
end
